create table if not exists users
(
    id        bigint generated by default as identity (maxvalue 2147483647)
        constraint users_pkey
            primary key,
    password  varchar(255),
    username  varchar(255)
        constraint uk_r43af9ap4edm43mmtq01oddj6
            unique
        constraint ukr43af9ap4edm43mmtq01oddj6
            unique,
    role      varchar(255),
    is_active boolean
);

create table if not exists department
(
    id          bigint generated by default as identity
        constraint department_pkey
            primary key,
    description varchar(255),
    name        varchar(255)
);

create table if not exists user_detail
(
    id            bigint generated by default as identity (maxvalue 2147483647)
        constraint user_detail_pkey
            primary key,
    first_name    varchar(255),
    last_name     varchar(255),
    position      varchar(255),
    user_id       bigint
        constraint fkr6i0t96qgu9l8l5nn2vqo8rcl
            references users,
    email         varchar(255),
    covid_status  varchar(255),
    department_id bigint
        constraint fk9ce3awoaynykmmfquk60ye42w
            references department,
    phone_number  varchar(255),
    risk_status   varchar(255),
    date_of_birth timestamp,
    constraint email_unique unique (email)
);

create table if not exists indicators
(
    id                   bigint generated by default as identity (maxvalue 2147483647)
        constraint indicators_pkey
            primary key,
    blood_oxygen         double precision,
    upper_blood_pressure integer,
    check_time           timestamp,
    heart_rate           integer,
    is_last              boolean,
    temperature          double precision,
    user_id              bigint
        constraint fkfwlshc8bvn9a55dbtgif3ps0q
            references users,
    lower_blood_pressure integer
);

create table if not exists notification
(
    id         bigint generated by default as identity (maxvalue 2147483647)
        constraint notification_pkey
            primary key,
    content    varchar(255),
    created_at timestamp,
    is_seen    boolean,
    user_id    bigint
        constraint fkfyjywnk7ylei4tkg7jpdbbp6b
            references users,
    topic      varchar(255)
);

create table if not exists task
(
    id              bigint generated by default as identity (maxvalue 2147483647)
        constraint task_pkey
            primary key,
    created_at      timestamp,
    employee_id     bigint
        constraint fkfyjywnk7ylei4tkg7jpdbbp6c
            references users,
    doctor_id       bigint
        constraint fkfyjywnk7ylei4tkg7jpdbbp6e
            references users,
    complaints      text,
    recommendations text
);
