server:
  port: 8067
spring:
  application:
    name: notification
  webflux:
    base-path: /notify
  main.allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5445/safespace-db
    username: safespace
    password: hc@*bvfS)4
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:8761/eureka/}
app:
  firebase-config-file: safespace-b67e3-firebase-adminsdk-tz383-7483a5c55e.json
