server:
  port: 8080
spring:
  application:
    name: gateway
  main.allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5445/safespace-db
    username: safespace
    password: hc@*bvfS)4
  cloud:
    gateway:
      routes:
        - id: BUSINESS
          uri: 'http://localhost:8077'
          predicates:
            - Path=/business/**
        - id: NOTIFICATION
          uri: 'http://localhost:8067'
          predicates:
            - Path=/notification/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:8761/eureka/}

springbootwebflux:
  jjwt:
    password:
      encoder:
        secret: myjwtsecret
        iteration: 33
        keylength: 256
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize
    expiration: 30000
