server:
  port: 8077
spring:
  application:
    name: business
  webflux:
    base-path: /business
  main.allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5445/safespace-db
    username: safespace
    password: hc@*bvfS)4
#  liquibase:
#    change-log: classpath:/db/changelog.xml
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:8761/eureka/}

